version: 2

builds:
  - main: ./cmd/shellguard
    binary: shellguard
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "shellguard_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - name: shellguard
    binaries:
      - shellguard
    repository:
      owner: jonchun
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/jonchun/shellguard
    description: MCP server for read-only shell access over SSH
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellguard"]
          end

checksum:
  name_template: checksums.txt

release:
  github:
    owner: jonchun
    name: shellguard
